theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/logo-white.svg'
  menu:
    primary:
      level_2:
        summary:
          active: true
          source: "Summary" # "Summary" | "meta_description"
          truncate: 250
  persons:
    sitemap:
      ignore_children: true
  events:
    sitemap:
      ignore_children: true