[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/actualites/2026-04-16-comment-vulgariser-les-donnees-sur-les-chaufferies-urbaines-un-defi-releve-hackathon-sante-durable/index.html"
to = "/actualites/2026-04-16-vulgariser-les-donnees-sur-les-chaufferies-urbaines-un-defi-releve-hackathon-sante-durable/"

[[redirects]]
from = "/marilou-vuillemet/index.html"
to = "/equipe/marilou-vuillemet/"

[[redirects]]
from = "/organisations/index.html"
to = "/partenaires/"

[[redirects]]
from = "/actualites/reponses-operationnelles/adaptation-au-changement-climatique/index.html"
to = "/actualites/cu/adaptation-au-changement-climatique/"

[[redirects]]
from = "/reponses-operationnelles/gestion-responsable-du-foncier/index.html"
to = "/usages/gestion-responsable-foncier/"

[[redirects]]
from = "/actualites/reponses-operationnelles/zan/index.html"
to = "/actualites/cu/zan/"

[[redirects]]
from = "/projet/orchestrer-les-donnees-du-territoire/index.html"
to = "/projet/orchestration/"

[[redirects]]
from = "/projet/un-enjeu-de-replicabilite/index.html"
to = "/projet/replicabilite/"

[[redirects]]
from = "/adaptation-au-changement-climatique/index.html"
to = "/usages/adaptation-changement-climatique/"

[[redirects]]
from = "/reponses-operationnelles/index.html"
to = "/usages/"

[[redirects]]
from = "/soutien-et-reseau/index.html"
to = "/reseau-et-soutien/"

[[redirects]]
from = "/actualites/reponses-operationnelles/qualite-air/index.html"
to = "/actualites/cu/qualite-air/"

[[redirects]]
from = "/reseau-soutien/index.html"
to = "/reseau-et-soutien/"

[[redirects]]
from = "/projet/projet-1/index.html"
to = "/projet/presentation/"

[[redirects]]
from = "/connaissance-du-territoire/index.html"
to = "/usages/adaptation-changement-climatique/"

[[redirects]]
from = "/actualites/2025-11-17-2-ans-de-projet-city-orchestra/index.html"
to = "/actualites/2025-11-17-evenement-2025/"

[[redirects]]
from = "/actualites/reponses-operationnelles/index.html"
to = "/actualites/cu/"

[[redirects]]
from = "/actualites/evenement/index.html"
to = "/actualites/evenements/"

[[redirects]]
from = "/actualites/qualite-air/index.html"
to = "/actualites/cu/qualite-air/"

[[redirects]]
from = "/gestion-responsable-du-foncier/index.html"
to = "/usages/gestion-responsable-foncier/"

[[redirects]]
from = "/projet/construire-la-gouvernance/index.html"
to = "/projet/gouvernance/"

[[redirects]]
from = "/usages/adaptation-au-changement-climatique/index.html"
to = "/usages/adaptation-changement-climatique/"

[[redirects]]
from = "/evaluation-de-lefficacite/index.html"
to = "/usages/amelioration-qualite-air/"

[[redirects]]
from = "/reponses-operationnelles/efficacite-energetique/index.html"
to = "/usages/efficacite-energetique/"

[[redirects]]
from = "/organisations/brest-metropole/index.html"
to = "/partenaires/brest-metropole/"

[[redirects]]
from = "/actualites/2023-11-02-city-orchestra-laureat-tid/index.html"
to = "/actualites/2023-06-07-city-orchestra-laureat-tid/"

[[redirects]]
from = "/agenda/2025/index.html"
to = "/2025/"

[[redirects]]
from = "/organisations/region-bretagne/index.html"
to = "/partenaires/region-bretagne/"

[[redirects]]
from = "/agenda/2025/03/index.html"
to = "/2025/03/"

[[redirects]]
from = "/actualites/reponses-operationnelles/efficacite-energetique/index.html"
to = "/actualites/cu/efficacite-energetique/"

[[redirects]]
from = "/reponses-operationnelles/adaptation-au-changement-climatique/index.html"
to = "/usages/adaptation-changement-climatique/"

[[redirects]]
from = "/actualites/adaptation-au-changement-climatique/index.html"
to = "/actualites/cu/adaptation-au-changement-climatique/"

[[redirects]]
from = "/efficacite-energetique/index.html"
to = "/usages/efficacite-energetique/"

[[redirects]]
from = "/projet/city-orchestra/index.html"
to = "/projet/presentation/"

[[redirects]]
from = "/organisations/ille-villaine/index.html"
to = "/partenaires/ille-villaine/"

[[redirects]]
from = "/actualites/2023-11-07-city-orchestra-laureat-tid/index.html"
to = "/actualites/2023-06-07-city-orchestra-laureat-tid/"

[[redirects]]
from = "/espace-ressources-1/index.html"
to = "/ressources/"

[[redirects]]
from = "/organisations/rennes-metropole/index.html"
to = "/partenaires/rennes-metropole/"

[[redirects]]
from = "/reponses-operationnelles/amelioration-de-la-qualite-de-l-air/index.html"
to = "/usages/amelioration-qualite-air/"

[[redirects]]
from = "/marilou-vuillemet/actualites/index.html"
to = "/equipe/marilou-vuillemet/actualites/"

[[redirects]]
from = "/amelioration-de-la-qualite-de-l-air/index.html"
to = "/usages/amelioration-qualite-air/"

[[redirects]]
from = "/partenaires/mipihsib/index.html"
to = "/partenaires/numihfrance/"

